<hr>
<b><font color='red'>Ejercicio 01</font></b>  

Selecciona las primera columna de la matriz `p` proporcionada, y guárdala en la variable `p1`. Sustituye los elementos de p1 que sean iguales a 0, por el valor $7$.

In [2]:
import numpy as np
p = np.array([[1,2,4],[0,0,0],[0,6,8]])
p1 = p[:, 0]
p1[p1==0] = 7
print(p1)
# Escribe tu código aquí

[1 7 7]


<hr>
<b><font color='red'>Ejercicio 02</font></b>  

Obtener una función que calcule la distancia forman dos vectores

$$
v=[v_1,v_2,v_3,...]
\newline
u=[u_1,u_2,u_3,...]
\newline
d=\sqrt{ (u_1-v_1)^2 + (u_2-v_2)^2 + (u_3-v_3)^2 + ... }
$$

In [6]:
def d(v, u):
    return np.sqrt(np.square(u[0] - v[0])+np.square(u[1] - v[1]))
    

v = np.array([1,-1])
u = np.array([0,1])

d(v,u) # El resultado debería de ser 2.2360679775 

2.23606797749979

<hr>
<b><font color='red'>Ejercicio 03</font></b>  

Obtener una función que calcule el coseno del ángulo que forman dos vectores

$$ \cos \theta = \frac{\langle v, u \rangle}{||v|| ||u||} $$

donde $|| v ||$ es la norma del vector v, que se puede expresar como $\sqrt{\langle v, v \rangle} = \sqrt{ v_1^2 +  v_2^2 +  v_3^2 + ... }$ y el producto escalar $\langle v, u \rangle = v_1 u_1 + v_2 u_2 + ...$


In [3]:
def cos(v, u):
    resultUp = (v[0] * u[0]) + (v[1] * u[1])
    resultDownLeft = np.sqrt(np.square(v[0]) + np.square(v[1]))
    resultDownRight = np.sqrt(np.square(u[0]) + np.square(u[1]))
    resultDown = resultDownLeft * resultDownRight
    return resultUp / resultDown

v = np.array([0,-1])
u = np.array([0,1])

cos(v,u)  # El resultado debería de ser -1.0

-1.0

<hr>
<b><font color='red'>Ejercicio 04</font></b>  

Vuelve hacer el ejercicio que hicimos en el cápitulo anterior, utilizando las funciones de numpy:

Crea una función que te devuelva la media y la desviación estándar de una lista ordenada.  
Pruébalo con lista = [4, 1, 11, 13, 2, 7]  
ayuda : https://es.wikipedia.org/wiki/Desviaci%C3%B3n_t%C3%ADpica

In [7]:
#hemos borrado las funciones, cambia el codígo siguiente

lista = [4, 1, 11, 13, 2, 7]
print(lista)
print("media = "+str(np.mean(lista))+" \u00B1 "+str(np.std(lista)))

[4, 1, 11, 13, 2, 7]
media = 6.333333333333333 ± 4.459696053419884


<hr>
<b><font color='red'>Ejercicio 05</font></b>  

Crear un array con 1 en el borde y  0 dentro

In [8]:
"""Esribe tu código aquí"""
array = np.zeros([10,10])
array[0, :] = 1
array[:, 0] = 1
array[9, :] = 1
array[:, 9] = 1
array
# la salida tiene que ser:
#array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

<hr>
<b><font color='red'>Ejercicio 06</font></b>  

Fíjate en el siguiente sistema de ecuaciones:
$$-x+y=1 \\ x+y=3$$

Escrito de forma matricial $(Ax = b)$:

$$
\begin{pmatrix}
-1 & 1\\
1 & 1 \\
\end{pmatrix}
\begin{pmatrix}
x\\
y\\
\end{pmatrix}
=
\begin{pmatrix}
1\\
3\\
\end{pmatrix}
$$

Podemos verla solución de forma gráfica

<img src="ecuaciones.png">

Supongamos que tenemos un sistema de n ecuaciones lineales con n incógnitas. Podemos representar el sistema de forma matricial como:
$$Ax=b$$
Si el sistema tiene una única solución (es compatible determinado), entonces la matriz $A$ es regular (determinante distinto de 0) y, por tanto, existe su matriz inversa $A^{−1}$.
Entonces, podemos multiplicar toda la ecuación por la inversa de $A^{−1}$:
$$A^{-1}\cdot Ax=A^{-1}\cdot b$$
$$x = A^{-1}\cdot b$$
Es decir, si la matriz $A$ es regular, entonces la matriz columna resultante del producto matricial $A^{−1} \cdot b $ contiene la solución del sistema $Ax=b$. 

In [9]:
A = np.array([[-1,1], [1, 1]])
b = np.array([1,3])
Ainv = np.linalg.inv(A)
resultado = np.dot(Ainv,b)
x = resultado[0]
y = resultado[1]
#busca como np hace la inversa de una matriz
"""Esribe tu código aquí"""

#Cuando tengas la matriz Ainv descomenta las siguientes lineas para comprobar el resultado
print("Ainv * A= ",np.dot(Ainv,A)) # la unidad
print("[x , y]= ",np.dot(Ainv,b))  #solución = 1,2 (ver gráfico)


Ainv * A=  [[1. 0.]
 [0. 1.]]
[x , y]=  [1. 2.]


<hr>
<b><font color='red'>Ejercicio 07</font></b> 

Utilizando la matriz de transición vista en el ejemplo de (Cadenas de Markov), pongamos el caso de una población de 1000 habitantes que en un momento inicial compran 1000 productos de la marca B, como sería la distribución de compras en la decima compra.

In [4]:

M = np.array([[0.6,0.3,0.1],[0.3,0.5,0.2],[0.4,0.3,0.3]])
print(M)
#Pongamos el caso de una población 1000 habitantes que en un momento inicial compran las marcas siguiendo la siguiente distribución:
V=np.array([1000,0,0])
#para estimar lo que sucederá en la siguiente compra tendremos que multiplica la matriz M por el vector V
V1=V.dot(M)
print(V1)
V2=V1.dot(M)
print("V2 = ",V2)
V3=V2.dot(M)
print("V3 = ",V3)
V4=V3.dot(M)
print("V4 = ",V4)
V5=V4.dot(M)
print("V5 = ",V5)
V6=V5.dot(M)
print("V6 = ",V6)
V7=V6.dot(M)
print("V7 = ",V7)
V8=V7.dot(M)
print("V8 = ",V8)
V9=V8.dot(M)
print("V9 = ",V9)
V10=V9.dot(M)
print("V10 = ",V10)

[[0.6 0.3 0.1]
 [0.3 0.5 0.2]
 [0.4 0.3 0.3]]
[600. 300. 100.]
V2 =  [490. 360. 150.]
V3 =  [462. 372. 166.]
V4 =  [455.2 374.4 170.4]
V5 =  [453.6  374.88 171.52]
V6 =  [453.232 374.976 171.792]
V7 =  [453.1488 374.9952 171.856 ]
V8 =  [453.13024 374.99904 171.87072]
V9 =  [453.126144 374.999808 171.874048]
V10 =  [453.125248  374.9999616 171.8747904]


<hr>
<b><font color='red'>Ejercicio 08</font></b>

En el siguiente juego, 3 niños y 3 niñas juegan a pasarse la pelota, si la probabilidad de pasar la pelota a la derecha o a su izquierda es la misma (1/2), crea la matriz de transición como hemos visto en clase, y obten la probabilidad de que la pelota llegue a 4 en la 3ª ronda si ha empezado en 1. 

sol : 0.25

<img src="pelota.gif">



In [34]:
import numpy as np
M = np.array([[0, 0.5, 0.5, 0, 0, 0],
              [0.5, 0, 0, 0.5, 0, 0],
              [0, 0.5, 0, 0, 0.5, 0],
              [0, 0, 0.5, 0, 0, 0.5],
              [0, 0, 0, 0.5, 0, 0.5],
              [0.5, 0, 0, 0, 0.5,0 ]])
M_cubed = np.linalg.matrix_power(M, 3)
probabilidad = M_cubed[0, 3]
print(M)
print(M_cubed[0, 3])

Matriz de transición M:
[[0.  0.5 0.5 0.  0.  0. ]
 [0.5 0.  0.  0.5 0.  0. ]
 [0.  0.5 0.  0.  0.5 0. ]
 [0.  0.  0.5 0.  0.  0.5]
 [0.  0.  0.  0.5 0.  0.5]
 [0.5 0.  0.  0.  0.5 0. ]]
0.25


<hr>
<b><font color='red'>Ejercicio 09</font></b>

En 1674 G. Leibnitz da la serie:
$$ \frac{\pi}{4} = 1-\frac{1}{3}+\frac{1}{5}-\frac{1}{7}+\frac{1}{9}+...$$
Es decir que:
$$ \pi = 4-\frac{4}{3}+\frac{4}{5}-\frac{4}{7}+\frac{4}{9}+...$$
Haz la serie hasta el termino $\frac{4}{10000}$, el resultado es 3.14139265359....

In [21]:
"""Esribe tu código aquí"""
n = 1
contador = 1 
resultado = 0
while n <= 10000:
    termino = 4 / n
    if contador % 2 == 0:
        resultado -= termino
    else:
        resultado += termino
    n += 2  # Siguiente término
    contador += 1
print(resultado)
terminos = 4 / n

3.141392653591791
